### ISSUE TITLE
Remove upcoming events when they're over

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/haystack-home#120]
Currently, we manually remove events from the community page. It would be nice if they disappeared from the UI when their date passed. Is it possible to do this?

**Comment by carlosgauci** [comment]
Hey @bilgeyucel sure I've opened a PR for it: https://github.com/deepset-ai/haystack-home/pull/122 just need to change the format of the date when the event is added

**Comment by bilgeyucel** [comment]
solved with #122
