### ISSUE TITLE
Minor layout bug

### ISSUE THREAD

**Issue by TuanaCelik** [deepset-ai/haystack-home#174]
On smaller screens we're getting this layour issue where the image is overlayed with the text. Would be nice to have a fix 🙏

![image (14)](https://github.com/deepset-ai/haystack-home/assets/15802862/9c7a1c28-8e3c-4c15-9c68-141f3d7c60ea)

**Comment by error-4u** [comment]
hello can i work on this issue 

OS : Ubuntu


current behaviour : 
file:///home/vboxuser/Pictures/Screenshots/Screenshot%20from%202023-09-22%2014-17-59.png


After :  file:///home/vboxuser/Pictures/Screenshots/Screenshot%20from%202023-09-22%2014-14-38.png

 **width: 30% ;**

**Comment by error-4u** [comment]
[img](file:///home/vboxuser/Pictures/Screenshots/Screenshot%20from%202023-09-22%2014-17-59.png)

**Comment by error-4u** [comment]
> On smaller screens we're getting this layour issue where the image is overlayed with the text. Would be nice to have a fix 🙏
> 
> ![image (14)](https://user-images.githubusercontent.com/15802862/255923520-9c7a1c28-8e3c-4c15-9c68-141f3d7c60ea.png)

hello can i work on this issue

OS : Ubuntu

current behaviour :
Screenshot from 2023-09-22 14-17-59
width: 35% ;

After :
Screenshot from 2023-09-22 14-14-38
width: 30% ;

@error-4u
