### ISSUE TITLE
Switching from 2.0 Beta to Stable 2.0

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/haystack-home#303]
- [x] Switch tutorial overview pages
    - https://haystack.deepset.ai/tutorials and https://haystack.deepset.ai/tutorials?v=2.0 should display 2.0 tutorials with the current banner
![image](https://github.com/deepset-ai/haystack-home/assets/25897116/cd1b6f42-9a7d-49bb-904b-324501a5d3c7)

    - https://haystack.deepset.ai/tutorials?v=1.0 should display 1.x tutorials (tutorials that dont have `haystack_2 = true`)
- [x] All `2.0-beta` tags should be `2.0` 
    *  "Haystack version" dropdown options should be `1.0` and `2.0` (not 2.0-beta)
    * Tags above "Tutorials" and "Documentation" should be `2.0`
    * Tutorial sidebar tags should be `2.0`
    * Tutorial cards should have **`2.0` tag with a star icon** (or any relevant icon), not `2.0-beta`
![image](https://github.com/deepset-ai/haystack-home/assets/25897116/215c4603-2f39-46ae-a76f-c4111b371ef2)

- [x] Remove 1.x tutorials from the sidebar (tutorials that dont have `haystack_2 = true`) and only display 2.0 tutorials
![image](https://github.com/deepset-ai/haystack-home/assets/25897116/f23014a7-9a66-47ca-9067-d982efa03155)

**Comment by TuanaCelik** [comment]
I've resolved the second point in the #304 PR, the first and third I leave to Carlos

**Comment by carlosgauci** [comment]
Also resolved the other points in the PR :)
