### ISSUE TITLE
Download button for tutorials

### ISSUE THREAD

**Issue by TuanaCelik** [deepset-ai/haystack-home#48]
Tutorials have the following in the frontmatter:
```
---
layout: tutorial
colab: https://colab.research.google.com/github/deepset-ai/haystack-tutorials/blob/main/tutorials/01_Basic_QA_Pipeline.ipynb
toc: True
title: "Build Your First QA System"
last_updated: 2022-10-12
level: "beginner"
weight: 10
description: Get Started by creating a Retriever Reader pipeline.
category: "QA"
aliases: ['/tutorials/first-qa-system']
---
```

We would like to also have a 'download' button at the top too. 

@masci - is it worth asking contributors to provide a `download` field in haystack-tutorials `index.toml` ? - I would imagine _everything_ should be 'downloadable'? In which case we could just re-use the colab field URL to download the file?

**Comment by carlosgauci** [comment]
It was added already, you just need to add the download key to the frontmatter, like the colab link.
![dl-btn](https://user-images.githubusercontent.com/53526597/200483493-d4d321fa-50aa-4f9d-b6a3-e9817a57f319.jpg)

**Comment by TuanaCelik** [comment]
Hey @carlosgauci - Yes indeed, but from what I remember there was still some functionality to add no? When I click that button I got a json file in the browser. It didn't download the `.ipynb` file. Or am I doing something wrong?

**Comment by carlosgauci** [comment]
@TuanaCelik You're right I opened a PR: https://github.com/deepset-ai/haystack-home/pull/49 to force downloads on the button. The files to be downloaded should be in the static directory though so I don't think you can re-use the same colab URL unless they provide a direct download link.

**Comment by TuanaCelik** [comment]
Ah ok, so the `.ipynb` files won't be in the haystack-home repo. They're in `haystack-tutoials`. Any way we could have them downloaded from the git url to the file?

**Comment by carlosgauci** [comment]
I think the best way would be to modify the build script that @masci added, to also copy over the .ipynb files into static/downloads, then you can serve the downloads from there easily.

**Comment by TuanaCelik** [comment]
Sounds good, wdyt @masci ?
