### ISSUE TITLE
Exclude some pages from sitemap.xml

### ISSUE THREAD

**Issue by TuanaCelik** [deepset-ai/haystack-home#55]
Let's implement a way to exclude some pages from the sitemap generation if needed. E.g. there's no need to have the versioned benchmarks in the sitemp, only haystack.deepset.ai/benchmarks
I found a way you can have an optional "private" or "sitemap_exclude" parameter in the frontmatter (I think) which will exclude it from being added to the sitemap. I think this is what this forum post explains: https://discourse.gohugo.io/t/disable-page-from-sitemap/37213/2

Do I understand this correctly @carlosgauci?

**Comment by carlosgauci** [comment]
@TuanaCelik yep that's correct, just added it: https://github.com/deepset-ai/haystack-home/pull/57
