### ISSUE TITLE
Make default color of tutorial header dark

### ISSUE THREAD

**Issue by TuanaCelik** [deepset-ai/haystack-home#63]
@bilgeyucel idk what you think but @carlosgauci pointed this out the other day:
Apart from the individual tutorials, all the headers are dark, and I think it looks better that way too.
Wdyt? Shall we change it so that individual tutorials also have dark headers by default?

**Comment by bilgeyucel** [comment]
I agree with you @TuanaCelik. If there is no specific reason to make the header light for tutorials, let's make them dark 👍
