### ISSUE TITLE
Tutorial overview page revamp

### ISSUE THREAD

**Issue by TuanaCelik** [deepset-ai/haystack-home#78]
@carlosgauci we can follow the progress of the tutorial overview page revamp here. Here is the sequence with which we can introduce the changes presented in [this figma design](https://www.figma.com/file/7VpNuFosV1EmXOKcrXvFO9/Haystack-Tutorials-Page?node-id=1%3A132&t=mhCKJylgkfaU5WYr-0)

- [x] First up let's start with the level filter and 'new' tag functionality
- [x] Next up the time to complete and task filters can be added. @bilgeyucel and I will have to implement this in `haystack-tutorials`
- [x] Next up the search with dC

**Comment by TuanaCelik** [comment]
On that note, here is the issue to add the time to complete and created at tags to the frontmatter: https://github.com/deepset-ai/haystack-tutorials/issues/108

I will create a separate issue for the 'new' tag too. @carlosgauci let me know what the best way to get that from the markdown would be.
`new: True`?
Or just look for a 
`new` tag? Although I'm not sure if that's valid syntax for the frontmatter..

**Comment by carlosgauci** [comment]
> On that note, here is the issue to add the time to complete and created at tags to the frontmatter: [deepset-ai/haystack-tutorials#108](https://github.com/deepset-ai/haystack-tutorials/issues/108)
> 
> I will create a separate issue for the 'new' tag too. @carlosgauci let me know what the best way to get that from the markdown would be. `new: True`? Or just look for a `new` tag? Although I'm not sure if that's valid syntax for the frontmatter..

`new: true` should work fine :)
