### ISSUE TITLE
Introduce the 'Sort by' filter in tutorials

### ISSUE THREAD

**Issue by TuanaCelik** [deepset-ai/haystack-home#86]
Hey @carlosgauci - we are ready to introduce the 'sorting' into the tutorials page.
We now have the following frontmatters being added to the tutorials:
e.g.:
```
created_at: 2023-11-01
last_updated: 2023-02-15
```
Could we have a sort by that the user can select to see the 'latest-oldest' tutorials (E.g. Sort by 'date created')
and also one to sort by latest updated - oldest updated (E.g. Sort by 'date updated)
And we could use these frontmatters above to do that. Wdyt?

**Comment by bilgeyucel** [comment]
Fixed with #94
