### ISSUE TITLE
Last commit date is not fetched from tutorials

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/haystack-home#90]
#89 is not working, no last update date is visible. This is probably tutorials are not kept in the repository (so last commit date is not fetched). 

Date info in available if I add md files manually and build the website: [example tutorial](https://haystack-home-apm0t7wq1-deepset-overnice.vercel.app/tutorials/test-tutorial)

**Comment by carlosgauci** [comment]
Yep it seems that .Gitinfo / .Lastmod is not available for these files. Didn't find any solution yet, probably best to revert back to last_updated for now.

**Comment by bilgeyucel** [comment]
This issue continues. Git history is fetched with #91 but haystack-home cannot use this info as markdown files are transferred into another folder (`/content/tutorials`) without git history.
